{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "83d1f474ab3a470f8027a404deb5d1a5", "detectedBy": ["AST_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "065a78fabbe55f89686eb90097707046", "repository": "http://git.eclipse.org/gitroot/jdt/eclipse.jdt.core.git", "fileName": "org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/ResolveTests.java", "commitBeforeChange": "27d7a3f1b3dd8726f49b3c45b8ae92fd365eeb4f", "commitAfterChange": "27ff50a9809c3e55581c713af1b876f5db7707ee", "methodNumberBeforeChange": 126, "methodNumberAfterChange": 126, "signatureBeforeChange": " public void testDuplicateTypeDeclaration7() throws CoreException, IOException", "signatureAfterChange": " public void testDuplicateTypeDeclaration7() throws CoreException, IOException", "diff": ["-\t\t", "-\t\t// The result should be \"Type [in Type.class [in test.p [in src [in Resolve]]]]\" but it is", "-\t\t// currently \"Type [in Type.class [in test.p [in bug119434.jar [in Resolve]]]]\". ", "-\t\t// This is caused by the bug 194432", "-\t\t// This test must be updated once bug 194432 will be fixed", "-\t\t\t\t\"Unexpected elements\",", "-\t\t\t\t\"Type [in Type.class [in test.p [in bug119434.jar [in Resolve]]]]\",", "-\t\t\t\telements", "+\t\t\t\"Unexpected elements\",", "+\t\t\t\"Type [in [Working copy] Type.java [in test.p [in src [in Resolve]]]]\",", "+\t\t\telements"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "fc0c9c6bf4696add1721443a71bf1de8", "repository": "http://git.eclipse.org/gitroot/jdt/eclipse.jdt.core.git", "fileName": "org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/junit/extension/TestCase.java", "commitBeforeChange": "2528937997399f978f8c04c6800f46f957dbd27f", "commitAfterChange": "2fdac50d0a994a41e3b73d3202a0de983b014e1d", "methodNumberBeforeChange": 9, "methodNumberAfterChange": 9, "signatureBeforeChange": "  private void printAssertionFailure(AssertionFailedError afe)", "signatureAfterChange": "  private void printAssertionFailure(AssertionFailedError afe)", "diff": ["-\tSystem.out.println(\"Catched assertion failure while running test \"+getName()+\":\");", "+\tSystem.out.println(\"Caught assertion failure while running test \"+getName()+\":\");"]}], "num": 60155}